version: '3.3'
# simple reverse proxy setup
services:
    rproxy: 
        build:
            context: ./servers/rproxy
        ports: 
            - 80:80
        restart: always
        volumes:
            - logs:/var/log/nginx
volumes:
    logs: {}
