version: '3.3'
# simple reverse proxy setup
services:
    rproxy: 
        build:
            context: ./servers/ssl
        ports: 
            - 80:80
            - 443:443
        restart: always
        volumes:
            - logs:/var/log/nginx
    # config for ssl
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
volumes:
    logs: {}
