version: '3.7'
# load balancer with multiple servers
services:
    loadbalancer: 
        build:
            context: ./servers/loadbalancer
        ports: 
            - 80:80
            # - 443:443
        restart: always
        volumes:
            - ./logs/lb:/var/log/nginx
    servera: 
        build: 
            context: ./servers/a
        restart: always
        volumes:
            - ./logs/a:/var/log/nginx
    serverb: 
        build:
            context: ./servers/b
        restart: always
        volumes:
            - ./logs/b:/var/log/nginx